management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-1146712406.us-east-2.elb.amazonaws.com:8080/eureka/
  instance:
    prefer-ip-address: true
spring:
  zipkin:
    locator:
      discovery:
        enabled: true
    baseurl: armszipkin
turbine:
  appConfig: armsmicroservice,armscalc
  clusterNameExpression: "'default'"